pr: none
trigger:
- master

name: 0.9.4-ci.$(Rev:r)

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    includesymbols: true
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'Build.BuildNumber'
    buildProperties: 'NoWarn="1573;1591;0419";Version=$(Build.BuildNumber)'
#   buildProperties: 'NoWarn="1573;1591;0419";AllowedOutputExtensionsInPackageBuildOutputFolder=".dll;.xml;.pdb"'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.*upkg'
    publishPackageMetadata: true
    nuGetFeedType: 'internal'
    publishVstsFeed: 'WTelegramClient/WTelegramClient'


