trigger:
- master

name: 0.7.0-alpha.$(Rev:r)

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: Assembly-Info-NetCore@2
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: '**/*.csproj'
    InsertAttributes: true
    FileEncoding: 'auto'
    WriteBOM: false
    PackageVersion: '$(Build.BuildNumber)'
    LogLevel: 'verbose'
    FailOnWarning: false
    DisableTelemetry: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    includesymbols: true
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'Build.BuildNumber'
    buildProperties: 'NoWarn=1591;AllowedOutputExtensionsInPackageBuildOutputFolder=".dll;.pdb;.xml"'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.*upkg'
    publishPackageMetadata: true
    nuGetFeedType: 'internal'
    publishVstsFeed: 'wiz0u'


