name: 'Telegram API issues'

on:
  issues:
    types: [labeled]

permissions:
  issues: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/support-requests@v3.0.0
        with:
          support-label: 'telegram api'
          issue-comment: >
            **Github Issues** should be used only for problems with the library itself.
            
            Questions about Telegram API usage should be asked on **StackOverflow** so the whole community can help and benefit.
            Click here to open a question: https://stackoverflow.com/questions/ask?tags=c%23+wtelegramclient+telegram-api
          close-issue: true
